name: samsung_wallet
description: Samsung Wallet Example Flutter plugin project.
version: 1.0.0
homepage:

environment:
  sdk: '>=2.14.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.monocsp.samsung_wallet
        pluginClass: SamsungWalletPlugin


