name: samsung_wallet
description: Samsung Wallet Example Flutter plugin project. This plugin based Samsung Wallet Android java package file.
version: 1.1.0
repository: https://github.com/monocsp/flutter_samsung_wallet

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
  # flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.monocsp.samsung_wallet
        pluginClass: SamsungWalletPlugin

  assets:
    - assets/wallet/
    - assets/wallet/buttons/rgb/
